### ISSUE TITLE
Errors are reported despite that Error Collector is disabled

### ISSUE THREAD

**Issue by VadimBelov** [newrelic/go-agent#16] opened 2016-09-01 06:20 UTC
When configuring **ErrorCollector.Enabled = false** one expects errors not to be reported to APM view ("Error Analytics" and "Errors" under EVENTS).
Despite this configuration errors still arrive.

Please see Pull request #15

**Comment by willnewrelic** [comment] 2016-09-01 20:04
Hi VadimBelov

If `ErrorCollector.Enabled` is set to false, errors and error events should not be captured due to the following conditional:
https://github.com/newrelic/go-agent/blob/master/internal_txn.go#L284

I don't see any code issues and everything works as expected in my tests.  Could you please try testing this again?

**Comment by VadimBelov** [comment] 2016-09-04 09:44
Hi willnewrelic,
The errors that I see reported in New Relic APM page ("Error Analytics" and "Errors" views under EVENTS section) are panic events that occur in the middle of a transaction.
Considering [https://github.com/newrelic/go-agent/blob/master/config.go#L68](this) we assume that nor "analytics events" neither "traced errors" (the views described above) should show events if Error Collector is disabled.

**Comment by willnewrelic** [comment] 2016-09-15 22:59
Hi VadimBelov 

I think I understand the issue now:

When `ErrorCollector.Enabled` is set to false, the go-agent still creates error metrics.  This shows that errors are happening on the "Errors" and "Error Analytics" pages, even though examples of these errors are not being captured.

Though this is intended behavior, I see how it could be surprising and confusing.  I will research this issue here, and we will either change the behavior or improve the documentation.

Expect an update next week.

**Comment by willnewrelic** [comment] 2016-10-06 23:14
Hi VadimBelov

Just released version 1.2.  This version has a fix:  Error metrics are no longer created when `ErrorCollector.Enabled` is set to false.  I am hopeful that this solves your issue!

Closing this issue:  Please reopen it if problems persist.

**Closed by willnewrelic** 2016-10-06 23:14 UTC
