### ISSUE TITLE
Cross Application Tracing Support

### ISSUE THREAD

**Issue by lattwood** [newrelic/go-agent#22] opened 2016-11-04 15:58 UTC
golang is a great microservice language, and there would be immense value in supporting Cross Application Tracing in that context, even if it means manually extracting/adding the `X-NewRelic-*` headers to http requests.

**Comment by lpetre** [comment] 2016-11-07 15:05
The [Android SDK](https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-android/install-configure/work-android-sdk-api#pre34) has `Agent.getCrossProcessId` which enables you to track HTTP calls between applications. I'd love to see something similar in this package, or something similar, so that I can augment calls that go between APM applications.

**Comment by willnewrelic** [comment] 2016-11-16 22:02
Hi lattwood

Thanks for the cross app tracing support interest.  This is definitely on our roadmap!

**Comment by jippi** [comment] 2017-03-14 19:23
Any update on this @willnewrelic ?

**Comment by sergeylanzman** [comment] 2017-03-17 11:21
@willnewrelic You have documentions about this? Maybe I try create support for this.

**Comment by belimawr** [comment] 2017-03-21 13:56
I agree that it would be a grate improvement!!!

I also agree with @lattwood even adding the headers manually wold be very helpful

**Comment by sergeylanzman** [comment] 2017-03-30 09:12
@willnewrelic Any update? You can write about header I want add this manually. We really need this.

**Comment by belimawr** [comment] 2017-04-04 02:22
+1

I really need this feature as well! Even if I have to add the headers manually it would be extremely helpful.

**Comment by belimawr** [comment] 2017-04-12 19:36
@willnewrelic any updates on this?

**Comment by fbjork** [comment] 2017-07-11 22:47
@willnewrelic Any update?

**Comment by zapient** [comment] 2017-07-12 03:21
+1 Would love this to be added

**Comment by lattwood** [comment] 2017-07-13 23:51
Just added this feature to DataDog's APM on a fork, for those still looking for this.

https://github.com/securityscorecard/dd-trace-go/commit/08a49a15721a30231ef41144a6ea8eb850d04d22

**Comment by nadavshatz** [comment] 2017-08-01 19:01
👍

**Comment by iaroslav-ciupin** [comment] 2017-10-06 17:47
+1 @willnewrelic Is there any progress on this feature? would be great to hear any news

**Comment by robertnewrelic** [comment] 2017-10-06 18:48
Hey everyone!  Thanks for you interest in adding Cross Application Tracing support to our Go agent.  We have a feature request opened internally and are actively working on its implementation as I write this.  I do not yet have an ETA for when it will be released, but know that it's coming soon!

**Comment by nadavshatz** [comment] 2017-10-10 08:09
@robertnewrelic why did you close the issue before the functionality is available?

**Comment by robertnewrelic** [comment] 2017-10-10 16:29
@nadavshatz You have a good point, let me reopen the issue until the functionality is available.  I had initially closed it as 'being an issue' since it is actively being worked on internally, but I realize I don't want to give the impression to the community that the issue is not being addressed.

Thank you for the feedback!

**Comment by LawnGnome** [comment] 2017-11-29 17:20
We have just released version 1.11 with CAT support — please give it a whirl!

**Closed by LawnGnome** 2017-11-29 17:20 UTC
Labels: roadmap
