### ISSUE TITLE
NewRelic Golang: Client timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by bondhan** [newrelic/go-agent#95] opened 2019-07-30 10:06 UTC
Hi there!

I got below error, I am using go v1.10.4 linux/amd64.

I am not behind any firewall or whatsoever. New Relic in java server (same network segment) that we have runs fine.

We have tried:
- Increasing the timeout to 60 seconds
- Use http2 in the server
- Using Postman return 503 with response:
{"exception":{"message":"Server Error","error_type":"RuntimeError"}}
- troubleshooting with ./nrdiag says “No Issues Found”

Below is our code:

    config := newrelic.NewConfig(os.Getenv("NEW_RELIC_APP_NAME"), os.Getenv("NEW_RELIC_KEY"))

    config.Logger = newrelic.NewDebugLogger(os.Stdout)

    app, err := newrelic.NewApplication(config)
    if err != nil {
        fmt.Println("Failed to create newrelic application", err)
        os.Exit(1)
    }

.................

        httpListener, err := net.Listen("tcp", *httpAddr)
        if err != nil {
            oldlog.Print("Error: ", err)
            logger.Log("transport", "HTTP", "during", "Listen", "err", err)
            os.Exit(1)
        }
        g.Add(func() error {
            logger.Log("transport", "HTTP", "addr", *httpAddr)
            return http.Serve(httpListener, nrgorilla.InstrumentRoutes(httpHandler, app))
        }, func(error) {
            httpListener.Close()
        })
    }

However this what we got,note some_key was removed:

    (28422) 2019/07/29 18:08:50.058559 {"level":"warn","msg":"application connect failure","context":{"error":"Post https://collector-001.eu01.nr-data.net/agent_listener/invoke_raw_method?license_key=some_key\u0026marshal_format=json\u0026method=connect\u0026protocol_version=17: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"}}

Any help is really appreciated!!

**Comment by newrelic-eheinlein** [comment] 2019-08-01 00:06
Hi! For this kind of error, one possibility is that it is some kind of transient error on the New Relic backend; we would generally suggest that you test again, and if you still get the same error, open up a ticket with our support team at http://support.newrelic.com/.  However, I checked with our support team, and it looks like you already have a ticket open there regarding this issue, so you're already on the right track! We will focus our troubleshooting efforts in that ticket and I'll close this issue out.

**Closed by newrelic-eheinlein** 2019-08-01 00:06 UTC

**Comment by tkivisik** [comment] 2019-08-02 08:37
Same error here

**Comment by newrelic-eheinlein** [comment] 2019-08-02 20:09
Hi @tkivisik - as mentioned above for things that like this we generally recommend working with our Support team, which can be reached directly though support.newrelic.com.  We will be monitoring this issue and working with our Support team directly if it turns out any changes need to be made to the Go Agent to resolve this issue.

**Comment by rpetre** [comment] 2019-08-06 16:40
I also detected this issue in some of our apps and I just figured out I can prevent this by downgrading to 2.8.1, which is what I will do to work around the issue, since I don't need any of the 2.9.0 features yet. It might be the same issue as OP is having or not, I haven't yet figured out the real cause.

If I have the time I will try to reproduce this on a simple application and maybe narrow down the cause, but I figured it's worth noting in case it helps someone else.

**Comment by newrelic-eheinlein** [comment] 2019-08-06 22:42
@bondhan @tkivisik @rpetre Thank you for reporting this issue!  We were able to narrow down the root cause to an issue with one of our backend services.  This has been remedied, and you should now be able to connect without any changes to your agent.  Please let us know if you continue to see the same issue.
