### ISSUE TITLE
3.23 Regression: parallel NewGoroutine calls result in data races

### ISSUE THREAD

**Issue by adomaskizogian** [newrelic/go-agent#748] opened 2023-06-27 13:04 UTC
We have observed that running application with race detector enabled (`-race`) it detects that parallel calls to `newrelic.FromContext(ctx).NewGoroutine()` results in data races.

No issues with `3.22`

sample code that calls `NewGoroutine`

```golang
func NewNewrelicGoroutineTransaction(ctx context.Context) (context.Context, *newrelic.Transaction){
   txn := newrelic.FromContext(ctx)
   if txn != nil {
    gTxn := txn.NewGoroutine()  
    ctx = newrelic.NewContext(ctx, gTxn)
    return  ctx, gTxn
  }
  return ctx, nil
}
```

```
WARNING: DATA RACE
Write at 0x00c0010cc6d8 by goroutine 2026:
  github.com/newrelic/go-agent/v3/newrelic.(*Transaction).NewGoroutine()
      /home/adomas.kizogian/go/pkg/mod/github.com/newrelic/go-agent/v3@v3.23.0/newrelic/transaction.go:502 +0x1db
```

**Comment by rittneje** [comment] 2023-07-15 13:30
@iamemilio This bug prevents us from upgrading from 3.22.1. Can you please resolve it? Also, this library ought to run its unit tests with the race detector, in order to detect such bugs during development.

**Comment by nr-swilloughby** [comment] 2023-07-19 18:42
We're working to release a fix for this ASAP.

**Comment by nr-swilloughby** [comment] 2023-07-31 23:18
Fix released

**Closed by nr-swilloughby** 2023-07-31 23:18 UTC
Labels: bug

**Comment by adomaskizogian** [comment] 2023-08-03 18:34
Thank you guys!

**Comment by rittneje** [comment] 2023-08-27 14:21
@nr-swilloughby In the future it would be nice to include fixes like this in the release notes.

**Comment by nr-swilloughby** [comment] 2023-09-01 21:58
@rittneje sorry about that. The release notes mentioned the fix that was made, which happened to be the cause of both a performance issue and the race condition, but neglected to actually say that it fixed the race condition as well. I'll make a note about that in the next release.
