### ISSUE TITLE
Documentation on pkg.go.dev not available due to licence file and tags

### ISSUE THREAD

**Issue by rogchap** [newrelic/go-agent#169] opened 2020-07-03 05:21 UTC
The recent change to the license file has caused the documentation to be removed from https://pkg.go.dev site:

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/270252/86434308-8713cd80-bd40-11ea-8536-7ff1fc17c3c1.png">

https://pkg.go.dev/github.com/newrelic/go-agent/v3/newrelic?tab=overview

**Comment by purple4reina** [comment] 2020-07-07 20:29
@rogchap Thanks for bringing this to our attention. We are working to address it.

**Comment by v3n** [comment] 2020-09-24 01:10
I think what's causing the problem is the repository layout. When using the major directory model, _everything_ must exist in that directory, including licenses/readmes.

https://github.com/golang/go/issues/41333#event-3770625091

I'd like to request the removal of the V3 directory, moving everything up to root and instead use the layout that Google uses for their Github library:

- https://github.com/google/go-github
- https://github.com/google/go-github/blob/master/go.mod

The major directory model has been causing pain for me, since the repository is unsearchable via Github without finding both v2 and v3 code.

**Comment by tydavis** [comment] 2020-12-17 21:24
I might have been a little overzealous, but the license file was copied to both the `v3` and `v3/newrelic` subdirectories to guarantee coverage.

**Comment by tydavis** [comment] 2021-01-07 20:46
#254 has been merged. When released, it should fix this issue.

**Comment by RichVanderwal** [comment] 2021-01-07 22:33
We're targeting a Monday afternoon (January 11, 2021) release.

**Comment by tydavis** [comment] 2021-01-11 23:39
https://pkg.go.dev/github.com/newrelic/go-agent/v3/newrelic -- Issue resolved as of 2021-01-11 3:40pm Pacific time.

**Comment by tydavis** [comment] 2021-05-11 20:07
@RichVanderwal Likely a tagging problem, yes. Once the tag for the 3.X series is pushed/scanned/updated, it should trigger an update. 

You could also try running: 

```
curl https://sum.golang.org/lookup/github.com/newrelic/go-agent/v3/integrations@3.12.0
```

**Comment by RichVanderwal** [comment] 2021-06-02 22:10
Still working on this. Testing the two updated integration packages nrawssdk-v2 and nrgrpc, and also with one un-updated integration, nrzap.

**Closed** 2021-06-25 17:58 UTC
