### ISSUE TITLE
Memory leak in Go 1.17 (http.Transport)

### ISSUE THREAD

**Issue by netrebel** [newrelic/go-agent#447] opened 2022-02-02 06:21 UTC
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

We started seeing a memory leak issue when we upgraded from Go 1.11.3 (no modules) to 1.17 (with go-modules). In the following graph memory utilization can be seen growing right after the upgrade on Dec 10. We had been running the agent (github.com/newrelic/go-agent/v3 v3.15.2) in Go 1.11.3 without any issues.

![mem-leak](https://user-images.githubusercontent.com/294448/152100236-bf3a1d70-2eb8-43d4-9db7-aa748c2903d9.jpg)

This is a high throughput service, the aggregated throughput of all our instances is:
![image](https://user-images.githubusercontent.com/294448/152101375-67a575cd-388b-44f1-97ff-13022ca24a4e.png)

When we ran `pprof` on one of the instances, we saw something similar to the comment in [go/issues/43966](https://github.com/golang/go/issues/43966#issuecomment-927198600):

```
      flat  flat%   sum%        cum   cum%
    1.50MB  5.07%  5.07%    12.04MB 40.70%  net/http.(*Transport).dialConn
         0     0%  5.07%    12.04MB 40.70%  net/http.(*Transport).dialConnFor
    8.03MB 27.14% 32.21%     8.03MB 27.14%  bufio.NewWriterSize (inline)
    6.02MB 20.36% 52.57%     6.02MB 20.36%  bufio.NewReaderSize (inline)
```

The workaround seems to be to create a new `http.Transport` each time. Looking at the code the problem could be that `collectorDefaultTransport` is a Global variable and therefore reused.
https://github.com/newrelic/go-agent/blob/master/v3/newrelic/transport.go#L18 

After removing the New Relic agent from our application, we confirmed that the memory leak is gone.

## Steps to Reproduce

We are not able to reproduce this in our development environment due to the low traffic there. But in theory, this could be reproduced in an application with a similar load running on Go 1.17 and NR agent version `github.com/newrelic/go-agent/v3 v3.15.2`

## Expected Behavior

Memory utilization should remain constant

## Your Environment

Running on Ubuntu:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```

## Additional context

There's a PR that potentially addresses this issue in Go: 
https://github.com/golang/go/pull/50799

But other libraries we use are not using a Global variable for `http.Transport` and therefore do not trigger the memory leak. I don't know if that is the standard way to work with `http.Transport`

**Comment by nr-swilloughby** [comment] 2022-02-02 22:58
Thank you for bringing this to our attention. We're looking into this and what the best way to mitigate this would be until the memory leak in `http.Transport` is fixed.

**Comment by rajuGT** [comment] 2022-02-14 21:32
@netrebel Thanks for reporting.

@nr-swilloughby even we encountered this issue recently once we moved our project from go 1.13 to 1.15. 
<img width="543" alt="image" src="https://user-images.githubusercontent.com/2203863/153949921-82e9b9e5-aee1-46c3-b070-ab553f6fc042.png">

**Comment by jeffyanta** [comment] 2022-02-16 01:57
We've managed to mitigate the issue by overriding the transaction pointer with an empty struct:
```
defer func() {
	txn.End()
	*txn = newrelic.Transaction{}
}()
```
Results from a high-volume service:
<img width="705" alt="Screen Shot 2022-02-15 at 8 56 11 PM" src="https://user-images.githubusercontent.com/5760385/154181565-ecba8d41-c668-4e75-9196-c1c503e64bfa.png">

**Comment by rittneje** [comment] 2022-02-18 04:19
@netrebel Based on the PR description, https://github.com/golang/go/pull/50799 is resolving a leak that occurs when interacting with an arbitrary number of hostnames. But (I assume?) this library would only be interacting with one hostname. So that might be a red herring. One way to confirm would be to take the change from https://github.com/golang/go/pull/50799 and manually apply it to your standard library, and see if it fixes your leak.

**Comment by jeffyanta** [comment] 2022-03-09 16:05
Is there an update on this issue? We've managed to mitigate the memory footprint as describe earlier. However, we're noticing CPU increase linearly over time on a service that processes periodic tasks. We tested that removing the following line of code resolves the issue:

```
ctx = newrelic.NewContext(ctx, m)
```

Graph showing the before and after effect of the change:
<img width="705" alt="Screen Shot 2022-03-09 at 10 55 36 AM" src="https://user-images.githubusercontent.com/5760385/157480559-0d373d0c-9136-4135-bb1c-1e9f936d5bd1.png">

**Comment by nr-swilloughby** [comment] 2022-03-09 21:09
Interesting data re: CPU increase. We'll look into that as well as the mitigation on the memory issue ASAP.

**Comment by saurabhjain940** [comment] 2022-05-31 10:11
Hi Team,

Do we have any update on this issue? We are also facing the same problem.

**Comment by iamemilio** [comment] 2022-05-31 14:04
TBH, we expected the Go team to have patched this a long time ago. We will re-asses and re-prioritize this though, since it seems to not be going away any time soon.

**Comment by sandip-bhoi-od** [comment] 2022-08-04 01:56
We are using go 1.18 with github.com/newrelic/go-agent/v3 v3.17.0 and seeing the OOM error.

![image](https://user-images.githubusercontent.com/99978921/182745408-b47baee0-502d-42fd-b877-e099cd9bce30.png)

We created a utility function to create the newrelic segments within transaction.

```go
func logNewRelicTransaction(ctx context.Context, query string, sqlStatement string, dbconfig dbConfig) *newrelic.DatastoreSegment {
	//logging should be non-disruptive. any error during this is absorbed
	defer func() {
		if r := recover(); r != nil {
			log.Debug(ctx, fmt.Sprintf("Panic absorbed: %v", r))
		}
	}()
	txn := newrelic.FromContext(ctx)
	operation := extractOperation(ctx, query)
	collection := extractTableName(ctx, operation, query)
	seg := &newrelic.DatastoreSegment{
		StartTime:          txn.StartSegmentNow(),
		Product:            newrelic.DatastorePostgres,
		Collection:         collection,
		Operation:          operation,
		ParameterizedQuery: sqlStatement,
		Host:               dbconfig.Host,
		PortPathOrID:       strconv.Itoa(dbconfig.Port),
		DatabaseName:       dbconfig.Name,
	}
	return seg
}
```

The segment is closed by caller function as below

```go
//new relic segment here
	seg := logNewRelicTransaction(ctx, query, sqlStatement, txn.Conn.DBConfig)
	defer seg.End()
```

**Comment by sandip-bhoi-od** [comment] 2022-08-04 02:10
@iamemilio I wanted to bring this to your attention, that we are using the latest version 1.18 and newrelic go agent v3.17.0

**Comment by nr-swilloughby** [comment] 2022-08-04 21:05
Thanks for the additional information.

**Comment by iamemilio** [comment] 2022-08-22 16:32
> We've managed to mitigate the issue by overriding the transaction pointer with an empty struct:
> 
> ```
> defer func() {
> 	txn.End()
> 	*txn = newrelic.Transaction{}
> }()
> ```
> 
> Results from a high-volume service: <img alt="Screen Shot 2022-02-15 at 8 56 11 PM" width="705" src="https://user-images.githubusercontent.com/5760385/154181565-ecba8d41-c668-4e75-9196-c1c503e64bfa.png">

My thought on this at first glance, is that the agent should not destroy transaction objects, even after they have been ended. There may be metadata or info that users want to gather from a completed transaction. So, if you create a bunch of transactions, they will retain their data if they are not deallocated. I would not consider this specific case a memory leak. I think your solution is appropriate for your specific usage pattern though. Would users want an explicit function that can be called to deallocate transaction objects? Something like `txn.Close()` ?

**Comment by iamemilio** [comment] 2022-08-22 16:35
We are still looking into resolving the memory leak regarding the http.Transport object, and want to dig into the cpu issues you were seeing when calling `ctx = newrelic.NewContext(ctx, txn)`.

**Comment by rittneje** [comment] 2022-08-22 17:20
> My thought on this at first glance, is that the agent should not destroy transaction objects, even after they have been ended. There may be metadata or info that users want to gather from a completed transaction. So, if you create a bunch of transactions, they will retain their data if they are not deallocated.

@iamemilio Why is the garbage collector alone not reclaiming memory once the transaction falls out of scope?

**Comment by iamemilio** [comment] 2022-08-22 17:50
Is that what is happening? I would need to see more the way the instrumentation code is written in your application to verify that. As far as I am aware, we are not doing anything to make that data persist. When a transaction is ended, the data we collect for a transaction is finalized and dumped into a cache that is drained periodically when data payloads are sent to our servers. That is the only thing calling `txn.End()` does. If the transaction object pointer stays in scope, it may not be able to be safely deallocated by the garbage collector, and we do not explicitly deallocate it for the reasons outlined above.

**Comment by zfedoran** [comment] 2022-08-22 18:03
Hi @iamemilio thanks for giving this a bit more attention but I’m not sure this is related to anything particular on the end user side. 

There are multiple codebase reporting this problem so it appears to be something fundamental rather than something about how an individual codebase is using the newrelic client.

**Comment by iamemilio** [comment] 2022-08-22 18:32
Agreed, I am definitely not saying that there is not a memory leak. We know that the issue with http.Transport is impacting us. We are going to address that first, and then we can loop back and see if the other issues persist. 

I do want to rule out the usage pitfalls I outlined above though.

**Comment by iamemilio** [comment] 2022-08-25 15:08
We were able to capture a slow linear growth in memory on the order of 0.2 Mb per hour in our own testing when running the [v3/examples/server](https://github.com/newrelic/go-agent/tree/master/v3/examples/server) overnight.

<img width="1617" alt="Screen Shot 2022-08-25 at 10 56 14 AM" src="https://user-images.githubusercontent.com/10124680/186702137-c8487cf4-f0a9-4bfa-810d-17e8d2147580.png">

**Comment by iamemilio** [comment] 2022-08-25 16:52
Folks who were seeing very drastic memory growth, I have not been able to reproduce that. Would you be willing to provide a reproducer?

**Comment by sandip-bhoi-od** [comment] 2022-08-25 16:55
@iamemilio We had a support case as well created with newrelic. Please let me know if we can have working session. We can  try reproducing this issue again.

**Comment by iamemilio** [comment] 2022-08-25 19:35
Yes, we can set that up. Please ask the support engineer who is handling your case to set a call up with the go-team, and we can take it from there! Thanks.

**Comment by Ak-x** [comment] 2022-10-03 16:57
This issue is now being prioritized by our team; to investigate the problem further and implement a solution.

**Comment by iamemilio** [comment] 2022-10-05 20:45
# Memory Leak Root Cause Analysis for Datastore Segments

Hi all, Thanks so much for working with us on this issue, and being patient. We worked along side one of the original reporters of the issue, and were able to completely remediate it in their environment. We wanted to post a formal writeup here to explain what the problem was, how we fixed it, and what the next troubleshooting steps for all of you should be.

## Root Cause

Here is a very simplified pseudo-code example of what caused the issue. 

```go
func mainLoop(app *newrelic.Application, db dbConfig, job chan Job) {
    ctx :=  context.TODO()                        (1)
 
    for {
        select {
        case <- ctx.Done():
           break
        case <- job:
           doDataTransaction(ctx, app, job)       (2)
        }
    }
}
 
func doDataTransaction(ctx context.Context, app *newrelic.Application, db dbConfig, job Job)
   txn := app.StartTransaction("my data transaction")
   ctx = newrelic.NewContext(ctx, txn)             (3)
 
   for _, dataOperation := range job.Batch() {
       doBusinessLogicSegment(ctx, db, dataOperation)
   }
 
   txn.End()                                       (4)
}
```

(1) A context is created to keep track of a flow of execution. This context is created at a very high code scope and exists outside the scope where transactions get created.

(2) This context gets passed into each function that executes a transaction with some business logic on a datastore.

(3) The `doDataTransaction` function creates a transaction, then calls [NewContext](https://github.com/newrelic/go-agent/blob/c6110878eac69902e7c5d8203aa64c4e3ea4cae6/v3/newrelic/context.go#L13-L17) to write the transaction pointer to a context. This function is intentionally named `NewContext` because it calls [context.WithValue()](https://pkg.go.dev/context#example-WithValue) which creates a copy of the original context with an added key value pair containing a pointer to the transaction object. By replacing the original context with this newly created context containing the transaction pointer, we are effectively passing the transaction up the stack to the `mainLoop()`.

(4) The business logic is executed and the transaction is ended. This does not explicitly delete the transaction data on heap by design, in case the metadata needs to be accessed after the transaction ends.

### Summary
The assumption being made is that the transaction is out of scope once it is ended in `doDataTransaction`, and it will be garbage collected. This is not the case though. Remember that in step 3, we added a pointer to the transaction data into our context which is part of the `mainLoop()` of our application. As long as the context object in the main loop is in scope, the go garbage collector sees that a variable is still in scope that references the data for a given transaction and is unable to delete its memory in heap.

## Solution Space

[Canonically](https://www.sohamkamani.com/golang/context-cancellation-and-values), a context should be used as a way to pass around "common scoped" data within an application. It's important to be aware of the fact that data can never be removed from contexts, and that data stored inside a context is in scope as long as that context object is also in scope. For these reasons, New Relic recommends against storing transaction data on context objects that exist outside the scope of a transaction.

If using contexts is important to the flow of your application, we recommend that you derive a new context object for each transaction. This will propagate the original context through the chain of function calls safely, without leaking transaction data. The Code that is out of the scope of the current transaction does not need to access this transaction's data, so writing it to a context object that is out of scope does not make sense.

```go
func mainLoop(app *newrelic.Application, db dbConfig, job chan Job) {
    ctx :=  context.TODO()                        
 
    for {
        select {
        case <- ctx.Done():
           break
        case <- job:
           doDataTransaction(ctx, app, job)       
        }
    }
}
 
func doDataTransaction(ctx context.Context, app *newrelic.Application, db dbConfig, job Job)
   txn := app.StartTransaction("my data transaction")

   // derive a new context to pass common data to code handling segments of this transaction
   txnContext := newrelic.NewContext(ctx, txn)        
 
   for _, dataOperation := range job.Batch() {
       doBusinessLogicSegment(txnContext, db, dataOperation)
   }
 
   txn.End()                                       
}
```

If your app does not access the transaction data from a context, then it really doesn't belong there in the first place. In this case you can just pass the pointer down through function arguments.

```go
func mainLoop(app *newrelic.Application, db dbConfig, job chan Job) {
    ctx :=  context.TODO()                        
 
    for {
        select {
        case <- ctx.Done():
           break
        case <- job:
           doDataTransaction(ctx, app, job)       
        }
    }
}
 
func doDataTransaction(ctx context.Context, app *newrelic.Application, db dbConfig, job Job)
   txn := app.StartTransaction("my data transaction")          
 
   for _, dataOperation := range job.Batch() {
        // pass the transaction pointer directly to the functions handling segments of this transaction
        doBusinessLogicSegment(ctx, db, dataOperation, txn)
   }
 
   txn.End()                                       
}
```

New Relic strongly recommends following the best practices outlined above. We understand that some users may assume that `txn.End()` removes all traces of transaction data when in fact it only signals the end of the transaction. The behavior of `txn.End()` is designed to retain that data and that behavior needs to be preserved, however a possible future enhancement could be to add another method, such as `txn.Close()` which can be called to remove the data explicitly. If this is something the community enthusiastically wants, the go team can consider it but there are trade offs with this approach too. It seems like the go authors thought of this exact scenario when designing the [context library](https://pkg.go.dev/context#pkg-overview), and it's probably best to follow the guidelines and best practices they laid out:

>Incoming requests to a server should create a Context, and outgoing calls to servers should accept a Context. The chain of function calls between them must propagate the Context, optionally replacing it with a derived Context created using WithCancel, WithDeadline, WithTimeout, or WithValue. When a Context is canceled, all Contexts derived from it are also canceled.
>
>The WithCancel, WithDeadline, and WithTimeout functions take a Context (the parent) and return a derived Context (the child) and a CancelFunc. Calling the CancelFunc cancels the child and its children, removes the parent's reference to the child, and stops any associated timers. Failing to call the CancelFunc leaks the child and its children until the parent is canceled or the timer fires. The go vet tool checks that CancelFuncs are used on all control-flow paths.

**Comment by iamemilio** [comment] 2022-10-11 19:54
We are going to consider this resolved for now. If you have gone through the troubleshooting steps outlined above, and are still having this problem in your environment, please re-open this ticket with information about your specific usage pattern and what you observed. Thanks!

**Closed by iamemilio** 2022-10-11 19:54 UTC
Labels: bug, PM, efficiency, Quality & UX
