### ISSUE TITLE
Infinite Tracing logging connection errors at too high a priority

### ISSUE THREAD

**Issue by newrelic-eheinlein** [newrelic/go-agent#213] opened 2020-08-14 18:08 UTC
## Description
A customer has reported seeing a lot of these error messages in the logs when Infinite Tracing is configured:
```
(8) 2020/08/11 14:23:07.972736 {"level":"error","msg":"trace observer response error","context":{"err":"rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: NO_ERROR"}}
```

After some investigation by the Infinite Tracing team, it looks like these are harmless, and we should log these as INFO/DEBUG errors (or not log them at all).

## Additional context
For New Relic employees - see these two Slack threads:
* https://newrelic.slack.com/archives/C0MQ534AD/p1597249643004300
* https://newrelic.slack.com/archives/CP36ZFEFQ/p1597250722002500

**Comment by blakeroberts-wk** [comment] 2020-09-11 19:15
Our go agents with infinite tracing configured have now started getting [this log](https://github.com/newrelic/go-agent/blob/c3a3f35d024eb89da7143a7ea9dad79981c0f5d9/v3/newrelic/trace_observer.go#L275-L280) about every 30 seconds per pod/container:

```
(1) 2020/09/11 19:04:39.113127 {"level":"error","msg":"trace observer response error","context":{"err":"EOF"}}
```

**Comment by Miriam-R** [comment] 2021-02-18 19:08
We're investigating whether this should be remediated on the service side.

**Comment by RichVanderwal** [comment] 2021-02-18 19:10
Internal NR thread [here](https://app.slack.com/client/T02D34WJD/CP36ZFEFQ/thread/CP36ZFEFQ-1613675339.123700).

**Comment by RichVanderwal** [comment] 2021-03-04 22:55
After some research, it appears that this error is coming from the HTTP2 layer, and is caused by the Infinite Tracing load balancers. We've decided to set up a reproduction, and to inhibit logging for this specific type of error.

**Comment by nr-swilloughby** [comment] 2021-03-12 00:59
We have successfully reproduced this issue and will focus on a code change to squelch it.
(23104) 2021/03/11 16:56:38.094567 {"level":"debug","msg":"trace observer response error","context":{"err":"rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: NO_ERROR"}}

**Comment by RichVanderwal** [comment] 2021-04-01 23:58
Hello @blakeroberts-wk , this issue should be fixed the the most recent release of the Go Agent, version [3.11.0](https://github.com/newrelic/go-agent/blob/master/CHANGELOG.md#3110). Please try it out and let us know if it works!

**Closed by RichVanderwal** 2021-04-01 23:58 UTC
Labels: bug, p2
