### ISSUE TITLE
/v3/integrations/logcontext/nrlogrusplugin: tests failures with Go 1.14 beta1

### ISSUE THREAD

**Issue by eclipseo** [newrelic/go-agent#134] opened 2020-02-13 18:43 UTC
Fedora 32 with Go 1.14 beta1, logrus 1.4.2:

```
github.com/newrelic/go-agent/v3/integrations/logcontext/nrlogrusplugin
--- FAIL: TestLogNoContext (0.00s)
    nrlogrusplugin_test.go:44: value for key method.name is incorrect:
        actual=github.com/sirupsen/logrus.(*Entry).Info
        expected=github.com/newrelic/go-agent/v3/integrations/logcontext/nrlogrusplugin.TestLogNoContext
--- FAIL: TestLogNoTxn (0.00s)
    nrlogrusplugin_test.go:44: value for key method.name is incorrect:
        actual=github.com/sirupsen/logrus.(*Entry).Info
        expected=github.com/newrelic/go-agent/v3/integrations/logcontext/nrlogrusplugin.TestLogNoTxn
--- FAIL: TestLogDistributedTracingDisabled (0.00s)
    nrlogrusplugin_test.go:44: value for key method.name is incorrect:
        actual=github.com/sirupsen/logrus.(*Entry).Info
        expected=github.com/newrelic/go-agent/v3/integrations/logcontext/nrlogrusplugin.TestLogDistributedTracingDisabled
--- FAIL: TestLogSampledFalse (0.00s)
    nrlogrusplugin_test.go:44: value for key method.name is incorrect:
        actual=github.com/sirupsen/logrus.(*Entry).Info
        expected=github.com/newrelic/go-agent/v3/integrations/logcontext/nrlogrusplugin.TestLogSampledFalse
--- FAIL: TestLogSampledTrue (0.00s)
    nrlogrusplugin_test.go:44: value for key method.name is incorrect:
        actual=github.com/sirupsen/logrus.(*Entry).Info
        expected=github.com/newrelic/go-agent/v3/integrations/logcontext/nrlogrusplugin.TestLogSampledTrue
--- FAIL: TestEntryUsedTwice (0.00s)
    nrlogrusplugin_test.go:44: value for key method.name is incorrect:
        actual=github.com/sirupsen/logrus.(*Entry).Info
        expected=github.com/newrelic/go-agent/v3/integrations/logcontext/nrlogrusplugin.TestEntryUsedTwice
    nrlogrusplugin_test.go:44: value for key method.name is incorrect:
        actual=github.com/sirupsen/logrus.(*Entry).Info
        expected=github.com/newrelic/go-agent/v3/integrations/logcontext/nrlogrusplugin.TestEntryUsedTwice
--- FAIL: TestEntryError (0.00s)
    nrlogrusplugin_test.go:44: value for key method.name is incorrect:
        actual=github.com/sirupsen/logrus.(*Entry).Info
        expected=github.com/newrelic/go-agent/v3/integrations/logcontext/nrlogrusplugin.TestEntryError
--- FAIL: TestWithCustomField (0.00s)
    nrlogrusplugin_test.go:44: value for key method.name is incorrect:
        actual=github.com/sirupsen/logrus.(*Entry).Info
        expected=github.com/newrelic/go-agent/v3/integrations/logcontext/nrlogrusplugin.TestWithCustomField
FAIL
exit status 1
FAIL	github.com/newrelic/go-agent/v3/integrations/logcontext/nrlogrusplugin	0.015s
```

Not sure if this is linked to Go 1.14 or not.

**Comment by purple4reina** [comment] 2020-02-13 19:18
Hi @eclipseo,

Thanks for filing this. I haven't been able to reproduce these failures. I have tested using your version of logrus and go1.14rc1 [docker image](https://hub.docker.com/_/golang). This leads me to the suspicion that the difference is coming based on your Fedora OS. I haven't tracked it down specifically, but the test failures in `method.name` come directly from logrus which uses a [`*runtime.Frame`](https://golang.org/pkg/runtime/#Frame). Maybe the difference is coming from the specific implementation of the `runtime` package on your machine?

Either way, I appreciate that you filed this as it could have been a possible error due to go 1.14. Fortunately this does not seem to be the case. This leads me to not being concerned by this.

Does this assessment fit your needs and expectations?

Thanks,
Rey

**Comment by newrelic-eheinlein** [comment] 2020-05-21 22:45
Hi @eclipseo,
We're going through older issues and wanted to check with you on this one. Go 1.14 has been released, and we haven't seen this problem in our local testing, or reported from elsewhere. Is this still an issue that you are seeing?

**Comment by purple4reina** [comment] 2020-05-28 17:48
Since we were unable to reproduce this and we see our tests now passing with go 1.14, I'm going to close this issue. Feel free to respond or re-open it if you feel there is more to discuss. 

Take care,
Rey

**Closed by purple4reina** 2020-05-28 17:48 UTC
