### ISSUE TITLE
observe raw SQL queries

### ISSUE THREAD

**Issue by ArchieY393** [newrelic/go-agent#391] opened 2021-10-06 16:36 UTC
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

I wish to see the raw SQL queries on newrelic transaction traces in 'Database Queries' tab but I see a string something like ‘select on 'table name' using MySQL’ which is not helpful.  I do see in other agents where there is an option to set the configuration to obfuscated/raw. Is there anything similar for Golang agent ?
However this is could be alternatively achieved using `ParameterizedQuery` in Datastore segment. But this seems to be burden if we've too many queries to turn into newrelic.DatastoreSegment. Can this be done implicitly when 'nrmysql' integration package is used ?

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

When "nrmysql" package is used to instrument the DB calls, the raw sql queries should be seen on newrelic UI. May be introduce an option to turn off the raw SQL if one doesn't like to disclose the data.

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

Able to see raw SQL on newrelic UI with minimal code changes to DB calls.
For eg: using ExecContext/QueryContext/QueryRowContext should do.

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by RichVanderwal** [comment] 2021-12-14 23:25
Hi @ArchieY393, we've made sure our Product Mananger sees this feature request to help prioritize work.

**Comment by iamemilio** [comment] 2022-10-05 15:53
closing as a duplicate of https://github.com/newrelic/go-agent/issues/208

**Closed as completed by iamemilio** 2022-10-05 15:53 UTC
Labels: enhancement
